---
title: "Evaluation of Craft Breweries in the <br> United States of America <br>"
author: "<br>Heindel Adu, Amy Markmum and Gabriel Gonzalez <br>- AGH Data Consult Inc."
date: "Spring 2019"
output: 
  html_document: 
    highlight: pygments
    keep_md: yes
    theme: united
---
#
#<br>
#

#### Load the necessary library packages prior to loading the data. I used the library(tidyr) and library(dplyr) . This will not show the code in the markdown file output in html.

```{r setup, include=FALSE}
library(tidyr)
library(dplyr)
library(plotly)
```
# <br>
##### 1. First read the beers data file Beers.csv and inspect the dataframe.

```{r}
library(readr)
Beers <- read_csv("Beers.csv")
head(Beers)
```

```{r}
Beers
```
```{r}
library(readr)
Breweries <- read_csv("Breweries.csv")
```
```{r}
head(Breweries)
```

```{r}
summary(Beers)
```
```{r}
summary(Breweries)
```

```{r}
names(Beers)
```
```{r}
names(Breweries)
```
```{r}
Beers <- rename(Beers, Brew_ID = Brewery_id)
names(Beers)
```

```{r}
fullData <- full_join(Breweries, Beers, by = "Brew_ID")
```

```{r}
fullData
```
```{r}
names(fullData)
```
```{r}
fullData <- rename(fullData, BreweryName = Name.x, BeerName = Name.y)
names(fullData)
```
```{r}
fullData %>%
  group_by(State) %>%
  summarise(count = n())

```
```{r}
BrewStatesC <- Breweries%>%
  group_by(State)%>%
  summarise(count = n())
```
```{r}
head(BrewStatesC)
BrewStatesC
```
```{r}
state.freq <- table(Breweries$State)
barplot(state.freq[order(state.freq)], 
        horiz = T,
        border = NA,
        xlim = c(0, 100),
        main = "Number of Breweries per State",
        xlab = "Number of Brewiews",
        ylab = "States")
```
#<br> 
# Number brewweries in each state:

```{r}
state.freq
```

```{r}
names(state.freq)
View(state.freq)
```

```{r}
sDF<-data.frame(state.freq)
names(sDF)
sDF<- rename(sDF, State = Var1, NoBreweries=Freq)
```

```{r}
View(sDF)
names(Breweries)
```
#<br>
```{r}
p1 <- plot_ly(Breweries, x = ~State) %>% add_histogram()
p2 <-Breweries %>%
  dplyr::count(State) %>%
  plot_ly(x = ~n, y = ~State) %>%
  add_bars(marker = list(color = 'rgba(170, 17, 19, 0.9)')) %>%
  layout(title = "Number of Breweries by State", 
         legend = list(x = 0.03, y = 1.04)) 
 

subplot(p2) 
```
#<br>